// <auto-generated />
namespace ProjektPortale.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class inicjalizacja_bazy1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inicjalizacja_bazy1));
        
        string IMigrationMetadata.Id
        {
            get { return "201606011339357_inicjalizacja_bazy1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
